cargo-features = ["named-profiles"]

[package]
name = "rs-ec-perf"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
rand = { version = "0.8", features = ["alloc"] }
fs-err = "2"

[dependencies]
reed-solomon-erasure = { version = "4.0", features = ["simd-accel"] }
# fffft = "*"
# ff = "*"
# subtle = "2.4"
# ffaster = { path = "../reed-solomon-erasure", features = ["simd-accel"] }
thiserror = "1.0.23"
# required for randomly dropping shards
rand = { version = "0.8", features = ["alloc"] }
itertools = "0.10"

[dev-dependencies]
iai = "0.1"
criterion = "0.3"

[profile.bench]
debug = true

[profile.dev]
debug = true

[profile.release]
debug = true

[[bench]]
name = "iai"
harness = false
bench = true

[[bench]]
name = "criterion"
harness = false
bench = true
