[package]
name = "rsc-perf"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reed-solomon-erasure = { version = "4.0", features = ["simd-accel"] }
fffft = "*"
ff = "*"

[dev-dependencies]
iai = "0.1"

# [[bench]]
