cargo-features = ["named-profiles"]

[package]
name = "rs-ec-perf"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reed-solomon-erasure = { version = "4.0", features = ["simd-accel"] }
polkadot-erasure-coding = { git = "git://github.com/paritytech/polkadot", package = "polkadot-erasure-coding" }
fffft = "*"
ff = "*"

rand = { version = "0.8", features = ["alloc"] }

[dev-dependencies]
iai = "0.1"

[profile.bench]
debug = true

[profile.dev]
debug = true

[profile.release]
debug = true

[[bench]]
name = "iai"
harness = false
bench = true
